### ISSUE TITLE
Error running theme with --safe flag

### ISSUE THREAD

**Issue by atom-morgan** [stackbit-themes/exto-nextjs#10]
I'm in the process of trying to host this theme on GitHub pages but the build is continually failing.

As a debugging measure, I read to ensure the Jekyll site runs without issues with the `--safe` flag which it does not.

However, I'm not exactly sure what the issue is here considering it all runs fine locally without the `--safe` flag. Here's my output running it with `bundle exec jekyll serve --safe --trace --verbose`:

Any ideas?

```
  Pre-Render Hooks: blog/green.md
  Rendering Markup: blog/green.md
  Rendering Layout: blog/green.md
     Layout source: site
         Rendering: blog/index.md
  Pre-Render Hooks: blog/index.md
  Rendering Markup: blog/index.md
  Rendering Layout: blog/index.md
     Layout source: site
  Liquid Exception: undefined method `map' for "/blog":String Did you mean? tap in /_layouts/blog.html
/Users/adammorgan/.rvm/gems/ruby-2.4.9/gems/jekyll-3.8.4/lib/jekyll/filters.rb:303:in `sort_input': undefined method `map' for "/blog":String (NoMethodError)
Did you mean?  tap
	from /Users/adammorgan/.rvm/gems/ruby-2.4.9/gems/jekyll-3.8.4/lib/jekyll/filters.rb:243:in `sort'
	from /Users/adammorgan/.rvm/gems/ruby-2.4.9/gems/liquid-4.0.1/lib/liquid/strainer.rb:56:in `invoke'
	from /Users/adammorgan/.rvm/gems/ruby-2.4.9/gems/liquid-4.0.1/lib/liquid/context.rb:86:in `invoke'
	from /Users/adammorgan/.rvm/gems/ruby-2.4.9/gems/liquid-4.0.1/lib/liquid/variable.rb:84:in `block in render'
```

**Comment by PGui** [comment]
I tried to host this template on github pages with the following Gemfile:
```
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "jekyll", "~> 3.8.4"
gem "github-pages"

group :jekyll_plugins do
    gem "jekyll-menus", "~> 0.6.0"
    gem "jekyll-paginate-v2", "~> 1.9"
    gem "jekyll-paginate", "~> 1.1"
end
```
and I ran into the same issue.

It seems to come from different issues:
* This theme needs jekyll 3.8.4 to run
* There is no version of the github-pages gem that depends on jekyll 3.8.4 according to here https://rubygems.org/gems/github-pages
* Using the github-pages gem, the get_pages() function from the _plugins/filters.rb file doesn't work, it doesn't seem to return the right type of object for the rest of the template to work (hence the `sort`  fails with the error you mentioned).

I'm no expert for this, but I used a workaround to make this work : I removed every reference to `get_pages` in template pages and directly filter my `site.pages` with liquid template like so :

![image](https://user-images.githubusercontent.com/8027479/104892778-e058ec80-5972-11eb-848f-19ba8afb47d5.png)
